# Media Stack

# Containers
# - Huntarr
# - Jellyfin
# - Jellyseerr
# - Kavita
# - Gluetun
# - Transmission
# - FlareSolverr
# - Autobrr
# - Prowlarr
# - Lidarr
# - Readarr
# - Radarr
# - Sonarr
# - Recyclarr
# - Bazarr
# - Homarr

# This setup is for running in my Unraid server

name: media

x-base-env: &base-env
  TZ: ${TZ:-Europe/London}
  UID: ${UID}
  GID: ${GID}
  PUID: ${UID}
  PGID: ${GID}
  UMASK: ${UMASK}

include:
  - networks.yml

services:

  jellyfin:
    extends:
      file: players/jellyfin.yml
      service: jellyfin
      
  jellyseerr:
    extends:
      file: requests/jellyseerr.yml
      service: jellyseerr

  huntarr:
    extends:
      file: managers/utilities/huntarr.yml
      service: huntarr

  gluetun:
    extends:
      file: vpns/gluetun.yml
      service: gluetun
  nzbget:
    extends:
      file: downloaders/nzbget.yml
      service: nzbget
  transmission:
    extends:
      file: downloaders/transmission.yml
      service: transmission
  transmission-lat-team:
    extends:
      file: downloaders/transmission.yml
      service: transmission-lat-team

  flaresolverr:
    extends:
      file: indexers/flaresolverr.yml
      service: flaresolverr

  prowlarr:
    extends:
      file: indexers/prowlarr.yml
      service: prowlarr

  radarr-movies-hd:
    extends:
      file: managers/radarr.yml
      service: radarr-movies-hd
  radarr-movies-anime-hd:
    extends:
      file: managers/radarr.yml
      service: radarr-movies-anime-hd

  sonarr-series-hd:
    extends:
      file: managers/sonarr.yml
      service: sonarr-series-hd
  sonarr-series-anime-hd:
    extends:
      file: managers/sonarr.yml
      service: sonarr-series-anime-hd

  recyclarr:
    extends:
      file: managers/utilities/recyclarr.yml
      service: recyclarr

  # kavita:
  #   extends:
  #     file: kavita.yml
  #     service: kavita

  # # autobrr:
  # #   extends:
  # #     file: autobrr.yml
  # #     service: autobrr

  # lidarr:
  #   extends:
  #     file: lidarr.yml
  #     service: lidarr

  # readarr-books:
  #   extends:
  #     file: readarr.yml
  #     service: readarr-books
  # readarr-audiobooks:
  #   extends:
  #     file: readarr.yml
  #     service: readarr-audiobooks

  # bazarr-anime:
  #   extends:
  #     file: bazarr.yml
  #     service: bazarr-anime
  # bazarr-hd:
  #   extends:
  #     file: bazarr.yml
  #     service: bazarr-hd
