# Enable/Disable Watchtower

services:
  immich-server:
    labels:
      - "com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE:-false}"
  immich-machine-learning:
    labels:
      - "com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE:-false}"
  redis:
    labels:
      - "com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE:-false}"
  database:
    labels:
      - "com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE:-false}"