# Found here: https://github.com/recyclarr/config-templates/blob/master/sonarr/templates/web-1080p-v4.yml

###################################################################################################
# Recyclarr Configuration Template: WEB-1080p (V4)                                                #
# Updated: 2024-10-02                                                                             #
# Documentation: https://recyclarr.dev                                                            #
# Note: If you are using multiple profiles in a single instance, please read the following        #
# documentation about file merging:                                                               #
# https://recyclarr.dev/reference/config-examples/#merge-single-instance                          #
# This config file is for use with Sonarr V4 only                                                 #
###################################################################################################

# Instance Definition: https://recyclarr.dev/reference/configuration/basic/
sonarr:
  media_sonarr_series_hd:
    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    media_naming:
      series: jellyfin-tvdb
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

    include:
      # Comment out any of the following includes to disable them
      - template: sonarr-quality-definition-series
      # Choose between the standard or alternative quality profile setup (choose one only)
      - template: sonarr-v4-quality-profile-web-1080p
      # - template: sonarr-v4-quality-profile-web-1080p-alternative
      - template: sonarr-v4-custom-formats-web-1080p

# Custom Formats: https://recyclarr.dev/reference/configuration/custom-formats/
    custom_formats:
      # Optional
      - trash_ids:
          # - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          # - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          # - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated     # using usenet
          # - 06d66ab109d4d2eddb2794d21526d140 # Retags         # using usenet
          # - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
          - name: WEB-1080p

      - trash_ids:
          # Uncomment the next six lines to allow x265 HD releases with HDR/DV
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        assign_scores_to:
          - name: WEB-1080p
            score: 0
      - trash_ids:
          - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
        assign_scores_to:
          - name: WEB-1080p

########### My Customs ###########

      # Just tags
      - trash_ids:
          - 1bd69272e23c5e6c5b1d6c8a36fce95e # HFR
          - cddfb4e32db826151d97352b8e37c648 # x264
          - e0c1a67f23908a55b6ae9834e8ed6727 # Single Episode
          - 4a20cfb76b5f92a8ca22b894b32e71be # Multi-Episode
        assign_scores_to:
          - name: WEB-1080p

      # Auto Boosts
      - trash_ids:
          - 3a4127d8aa781b44120d907f2cd62627 # Hybrid           # 100
          - b735f09d3c025cbb7d75a5d38325b73b # Remaster         # 25
          - 290078c8b266272a5cc8e251b5e2eb0b # 1080p            # 50
          - ec8fa7296b64e8cd390a1600981f3923 # Repack/Proper    # 5
          - eb3d5cc0a2be0db205fb823640db6a3c # Repack2          # 6
          - 44e7c4de10ae50265753082e5dc76047 # Repack3          # 7
          - d7c747094a7c65f4c2de083c24899e8b # FreeLeech        # 1
        assign_scores_to:
          - name: WEB-1080p

     # Custom boosts
      - trash_ids:
          - c9eafd50846d299b862ca9bb6ea91950 # x265
        assign_scores_to:
          - name: WEB-1080p
            score: 1

      - trash_ids:
          - 7ba05c6e0e14e793538174c679126996 # Multi
        assign_scores_to:
          - name: WEB-1080p
            score: 10

      - trash_ids:
          - 3bc5f395426614e155e585a2f056cdf1 # Season Pack
        assign_scores_to:
          - name: WEB-1080p
            score: 10

      # Lat-Team
      - trash_ids:
          - lat-team
        assign_scores_to:
          - name: WEB-1080p
            score: 10

      # Custom languages
      - trash_ids:
          - language-prefer-original-and-english-and-latino
          - language-prefer-original-and-english-and-spanish
        assign_scores_to:
          - name: WEB-1080p
            score: 30
      - trash_ids:
          - language-prefer-english-and-latino
          - language-prefer-english-and-spanish
        assign_scores_to:
          - name: WEB-1080p
            score: 20
      - trash_ids:
          - language-prefer-original-and-english
          - language-prefer-original-and-latino
          - language-prefer-original-and-spanish
        assign_scores_to:
          - name: WEB-1080p
            score: 15
      - trash_ids:
          - language-prefer-original
        assign_scores_to:
          - name: WEB-1080p
            score: 8
      - trash_ids:
          - language-prefer-english
          - language-prefer-spanish
        assign_scores_to:
          - name: WEB-1080p
            score: 5
      - trash_ids:
          - language-prefer-english-in-title
          - language-prefer-spanish-in-title
        assign_scores_to:
          - name: WEB-1080p
            score: 1
      - trash_ids:
          - language-not-original-or-english-or-spanish
        assign_scores_to:
          - name: WEB-1080p
            score: -30
##################################
